### ISSUE TITLE
When using multiple pickers on one page all of them will react to swiping

### ISSUE THREAD

**Issue by doop-lan** [VanishMax/picker#4]
Like the title says, whenever I include multiple pickers on one page they will all react to swiping anywhere on screen.

**Comment by VanishMax** [comment]
Hi, @ReadySetDice! I'm currently busy on another projects, but I'd love to accept PRs if you would like to make them

**Comment by doop-lan** [comment]
Hey @VanishMax in the end I decided to actually implement it like a normal person, so now I open a bottom drawer with a single wheel and only for mobile clients.

**Comment by VanishMax** [comment]
@ReadySetDice Ok, that's cool! Do you mean that this issue is now irrelevant for you?
Also, is the linked PR still active?

**Comment by doop-lan** [comment]
Hey @VanishMax, sorry for this super late response but it indeed is now irrelevant for me.
